name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Run Docker Images
      run: docker-compose -f docker/docker-compose.yml up -d
    - name: Install dependencies
      run: dotnet tool install --global Minimig --add-source https://www.myget.org/F/minimig/api/v3/index.json
    - name: Verify Mig Installation
      run: mig --version
    - name: Sleep # The Sql Server docker image needs time to accept connections
      run: sleep 10s
    - name: Run Migrations
      run: mig --folder="Migrations/SqlServer" --connection="Server=.,1433;Database=master;User Id=sa;Password=$SQLSERVER_PASSWORD;"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  SQLSERVER_PASSWORD: P@ssword123