name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Run Sql Server Image
      run: docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$SQL_PASSWORD" -p 1433:1433 --name sql-env -d mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    - name: Install dependencies
      run: dotnet tool install --global Minimig --add-source https://www.myget.org/F/minimig/api/v3/index.json
    - name: Verify Mig Installation
      run: mig --version
    - name: Move folder
      run: cd Migrations
    - name: Show me where i am at
      run: pwd
    - name: Sleep
      run: sleep 10s
    - name: Run Migrations
      run: mig --connection="$SQL_CONNECTION"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  SQL_PASSWORD: P@ssword123
  SQL_CONNECTION: 'Server=.,1433;Database=master;User Id=sa;Password=$SQL_PASSWORD;'
